In [1]:
from numpy import exp, array, random, dot

In [2]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

In [3]:
training_set_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [4]:
training_set_outputs

array([[0],
       [1],
       [1],
       [0]])

In [8]:
class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        self.synaptic_weights = 2 * random.random((3, 1)) - 1
        print(self.synaptic_weights)
        
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        print("x ", x)
        return x * (1 - x)

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        #output = sigmoid(dot(mat)
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)
            print(output)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            print("training_set_inputs.T ", training_set_inputs.T)
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

https://www.youtube.com/watch?v=157JtMJUlko&ab_channel=Orblitz and https://www.youtube.com/watch?v=tIeHLnjs5U8&t=489s&ab_channel=3Blue1Brown -> back propogation notes 

In [9]:
neural_network = NeuralNetwork()

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [10]:
neural_network.train(training_set_inputs, training_set_outputs, 1)

[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
training_set_inputs.T  [[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]
x  [[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
